### ISSUE TITLE
Logo Design: Mapbox Elevation

### ISSUE THREAD

**Issue by baranpirincal** [NotWoods/mapbox-elevation#1]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by NotWoods** [comment]
Hi Baran!

Thank you so much for the offer, I'm sorry I'm so late in replying. I really appreciate the gesture, but I don't maintain this project much so I feel that you should contribute to more active repos that deserve a great logo :smile:.

It seems that you're already creating logos in other repos, so I wish you the best of luck! It's great to see people contributing.

**Comment by baranpirincal** [comment]
@NotWoods 

Thanks a lot for your kindly comments!

Good luck! :)
