### ISSUE TITLE
Did you resample the downloaded rgb from mapbox?

### ISSUE THREAD

**Issue by delebash** [NotWoods/mapbox-elevation#3]
I know this project is old.  However, according to mapbox the largets size png you can download is 512x512 but your image is 1536x1536.  Did you download this per https://api.mapbox.com/v4/mapbox.terrain-rgb/{zoom}/{x}/{y}{@2x}.pngraw?access_token=YOUR_MAPBOX_ACCESS_TOKEN

Thanks,

**Comment by NotWoods** [comment]
I stitched together 9 tiles to create the larger image using a regular photo editor like Photoshop or MS Paint.
